-- Add question-set classification and real-exam question-set configuration.

create table if not exists public.question_sets (
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.spaces(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (space_id, name)
);

alter table public.questions
add column if not exists question_set_id bigint references public.question_sets(id) on delete set null;

alter table public.spaces
add column if not exists real_exam_name text,
add column if not exists real_question_sets jsonb not null default '[]'::jsonb;

insert into public.question_sets (space_id, name)
select s.id, 'Mặc định'
from public.spaces s
where not exists (
  select 1
  from public.question_sets qs
  where qs.space_id = s.id
);

update public.questions q
set question_set_id = qs.id
from public.question_sets qs
where qs.space_id = q.space_id
  and qs.name = 'Mặc định'
  and q.question_set_id is null;

alter table public.question_sets enable row level security;

drop policy if exists "question sets public read published" on public.question_sets;
create policy "question sets public read published"
on public.question_sets for select to anon
using (
  exists (select 1 from public.spaces s where s.id = space_id and s.published)
);

drop policy if exists "question sets admins manage" on public.question_sets;
create policy "question sets admins manage"
on public.question_sets for all to authenticated
using (public.can_manage_space(space_id))
with check (public.can_manage_space(space_id));

grant select on public.question_sets to anon;
grant select, insert, update, delete on public.question_sets to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant select (id, space_id, question_set_id, order_no, type, content, options_json) on public.questions to anon;

notify pgrst, 'reload schema';
