-- vn.Quiz cloud administration schema.
-- Run after quiz_attempts.sql and the mode/metadata migrations.
-- Then run real_exams_v2.sql, real_exam_revisions.sql, and delete_question_set_cascade.sql in that order.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  fullname text not null,
  role text not null check (role in ('superadmin', 'admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.spaces (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  timer_seconds integer not null default 60 check (timer_seconds > 0),
  exam_start_time time,
  allowed_late_minutes integer not null default 30 check (allowed_late_minutes > 0),
  real_exam_enabled boolean not null default false,
  real_question_percent integer not null default 50 check (real_question_percent in (30, 50, 70, 100)),
  real_timer_seconds integer not null default 60 check (real_timer_seconds in (45, 60, 90, 120)),
  real_multi_percent integer not null default 50 check (real_multi_percent in (30, 50, 70, 100)),
  real_max_attempts integer not null default 1 check (real_max_attempts between 1 and 5),
  real_scoring_method integer not null default 1 check (real_scoring_method in (1, 2)),
  real_exam_name text,
  real_question_sets jsonb not null default '[]'::jsonb,
  mock_result_retention_days integer not null default 7 check (mock_result_retention_days between 3 and 15),
  real_result_retention_exams integer not null default 7 check (real_result_retention_exams between 3 and 15),
  real_exam_version text not null default gen_random_uuid()::text,
  real_start_at timestamptz,
  real_end_at timestamptz,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    not real_exam_enabled
    or (real_start_at is not null and real_end_at is not null and real_start_at < real_end_at)
  )
);

alter table public.spaces
add column if not exists real_exam_version text;

alter table public.spaces
add column if not exists real_scoring_method integer not null default 1;

alter table public.spaces
add column if not exists real_exam_name text,
add column if not exists real_question_sets jsonb not null default '[]'::jsonb,
add column if not exists mock_result_retention_days integer,
add column if not exists real_result_retention_exams integer;

update public.spaces
set
  mock_result_retention_days = coalesce(mock_result_retention_days, 7),
  real_result_retention_exams = coalesce(real_result_retention_exams, 7);

alter table public.spaces
alter column mock_result_retention_days set default 7,
alter column mock_result_retention_days set not null,
alter column real_result_retention_exams set default 7,
alter column real_result_retention_exams set not null;

alter table public.spaces
drop constraint if exists spaces_mock_result_retention_days_check,
drop constraint if exists spaces_real_result_retention_exams_check;

alter table public.spaces
add constraint spaces_mock_result_retention_days_check check (mock_result_retention_days between 3 and 15),
add constraint spaces_real_result_retention_exams_check check (real_result_retention_exams between 3 and 15);

update public.spaces
set real_exam_version = gen_random_uuid()::text
where real_exam_version is null;

alter table public.spaces
alter column real_exam_version set default gen_random_uuid()::text,
alter column real_exam_version set not null;

create table if not exists public.space_admins (
  user_id uuid not null references public.profiles(id) on delete cascade,
  space_id bigint not null references public.spaces(id) on delete cascade,
  primary key (user_id, space_id)
);

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.spaces(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (space_id, name)
);

create table if not exists public.question_sets (
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.spaces(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (space_id, name)
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.spaces(id) on delete cascade,
  question_set_id bigint references public.question_sets(id) on delete cascade,
  order_no integer not null,
  type text not null check (type in ('single', 'multi')),
  content text not null,
  options_json jsonb not null,
  correct_json jsonb not null,
  created_at timestamptz not null default now(),
  unique (space_id, order_no)
);

create index if not exists questions_space_order_idx
on public.questions (space_id, order_no);

alter table public.questions
add column if not exists question_set_id bigint references public.question_sets(id) on delete set null;

alter table public.quiz_attempts
add column if not exists real_exam_version text,
add column if not exists real_exam_name text,
add column if not exists real_exam_start_at timestamptz,
add column if not exists real_exam_end_at timestamptz;

create index if not exists quiz_attempts_real_exam_export_idx
on public.quiz_attempts (space_slug, mode, real_exam_version, submitted_at desc);

create or replace function public.prevent_last_group_delete()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if exists (select 1 from public.spaces where id = old.space_id)
     and (select count(*) from public.groups where space_id = old.space_id) <= 1 then
    raise exception 'Space phải có ít nhất 1 Group';
  end if;
  return old;
end;
$$;

drop trigger if exists groups_keep_one on public.groups;
create trigger groups_keep_one
before delete on public.groups
for each row execute function public.prevent_last_group_delete();

create or replace function public.is_superadmin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'superadmin' and active
  );
$$;

create or replace function public.can_manage_space(target_space_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_superadmin() or exists (
    select 1
    from public.space_admins sa
    join public.profiles p on p.id = sa.user_id
    where sa.user_id = auth.uid()
      and sa.space_id = target_space_id
      and p.active
  );
$$;

revoke all on function public.is_superadmin() from public;
revoke all on function public.can_manage_space(bigint) from public;
grant execute on function public.is_superadmin() to authenticated;
grant execute on function public.can_manage_space(bigint) to authenticated;
grant execute on function public.can_manage_space(bigint) to anon;

create or replace function public.get_space_public_status(requested_slug text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select case
    when s.id is null then jsonb_build_object('exists', false, 'published', false)
    else jsonb_build_object('exists', true, 'published', s.published)
  end
  from (select 1) seed
  left join public.spaces s on s.slug = requested_slug
  limit 1;
$$;

revoke all on function public.get_space_public_status(text) from public;
grant execute on function public.get_space_public_status(text) to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.spaces enable row level security;
alter table public.space_admins enable row level security;
alter table public.groups enable row level security;
alter table public.question_sets enable row level security;
alter table public.questions enable row level security;

drop policy if exists "profiles read own or superadmin" on public.profiles;
create policy "profiles read own or superadmin"
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_superadmin());

drop policy if exists "profiles superadmin manage" on public.profiles;
create policy "profiles superadmin manage"
on public.profiles for all to authenticated
using (public.is_superadmin())
with check (public.is_superadmin());

drop policy if exists "spaces public read published" on public.spaces;
create policy "spaces public read published"
on public.spaces for select to anon
using (published);

drop policy if exists "spaces admins manage" on public.spaces;
create policy "spaces admins manage"
on public.spaces for all to authenticated
using (public.can_manage_space(id))
with check (public.is_superadmin() or public.can_manage_space(id));

drop policy if exists "space admins authorized read" on public.space_admins;
create policy "space admins authorized read"
on public.space_admins for select to authenticated
using (user_id = auth.uid() or public.is_superadmin());

drop policy if exists "space admins superadmin manage" on public.space_admins;
create policy "space admins superadmin manage"
on public.space_admins for all to authenticated
using (public.is_superadmin())
with check (public.is_superadmin());

drop policy if exists "groups public read published" on public.groups;
create policy "groups public read published"
on public.groups for select to anon
using (
  exists (select 1 from public.spaces s where s.id = space_id and s.published)
);

drop policy if exists "groups admins manage" on public.groups;
create policy "groups admins manage"
on public.groups for all to authenticated
using (public.can_manage_space(space_id))
with check (public.can_manage_space(space_id));

drop policy if exists "questions public read published" on public.questions;
create policy "questions public read published"
on public.questions for select to anon
using (
  exists (select 1 from public.spaces s where s.id = space_id and s.published)
);

drop policy if exists "questions admins manage" on public.questions;
create policy "questions admins manage"
on public.questions for all to authenticated
using (public.can_manage_space(space_id))
with check (public.can_manage_space(space_id));

drop policy if exists "question sets public read published" on public.question_sets;
create policy "question sets public read published"
on public.question_sets for select to anon
using (
  exists (select 1 from public.spaces s where s.id = space_id and s.published)
);

drop policy if exists "question sets admins manage" on public.question_sets;
create policy "question sets admins manage"
on public.question_sets for all to authenticated
using (public.can_manage_space(space_id))
with check (public.can_manage_space(space_id));

revoke all on public.profiles, public.spaces, public.space_admins, public.groups, public.question_sets, public.questions from anon;
grant select on public.spaces to anon;
grant select on public.groups to anon;
grant select on public.question_sets to anon;
grant select (id, space_id, question_set_id, order_no, type, content, options_json) on public.questions to anon;

grant select, insert, update, delete on public.profiles, public.spaces, public.space_admins, public.groups, public.question_sets, public.questions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.clear_question_set_questions(target_question_set_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_set public.question_sets%rowtype;
  target_space public.spaces%rowtype;
  deleted_question_count integer;
begin
  select *
  into target_set
  from public.question_sets
  where id = target_question_set_id
  for update;

  if not found then
    raise exception 'Ngân hàng câu hỏi không tồn tại.';
  end if;

  if not public.can_manage_space(target_set.space_id) then
    raise exception 'Bạn không có quyền quản lý Space này.';
  end if;

  select *
  into target_space
  from public.spaces
  where id = target_set.space_id
  for update;

  if target_space.real_exam_enabled
     and target_space.real_start_at is not null
     and target_space.real_end_at is not null
     and now() between target_space.real_start_at and target_space.real_end_at then
    raise exception 'Không thể xóa câu hỏi khi Đợt thi thật đang diễn ra. Hãy chờ đợt thi kết thúc hoặc điều chỉnh thời gian Thi thật.';
  end if;

  select count(*)
  into deleted_question_count
  from public.questions
  where question_set_id = target_question_set_id;

  delete from public.questions
  where question_set_id = target_question_set_id;

  update public.spaces
  set updated_at = now()
  where id = target_set.space_id;

  return jsonb_build_object(
    'question_set_id', target_question_set_id,
    'name', target_set.name,
    'deleted_questions', deleted_question_count
  );
end;
$$;

create or replace function public.delete_question_set_cascade(target_question_set_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_set public.question_sets%rowtype;
  target_space public.spaces%rowtype;
  remaining_config jsonb;
  set_count integer;
  deleted_question_count integer;
begin
  select *
  into target_set
  from public.question_sets
  where id = target_question_set_id
  for update;

  if not found then
    raise exception 'Ngân hàng câu hỏi không tồn tại.';
  end if;

  if not public.can_manage_space(target_set.space_id) then
    raise exception 'Bạn không có quyền quản lý Space này.';
  end if;

  select *
  into target_space
  from public.spaces
  where id = target_set.space_id
  for update;

  if target_space.real_exam_enabled
     and target_space.real_start_at is not null
     and target_space.real_end_at is not null
     and now() between target_space.real_start_at and target_space.real_end_at then
    raise exception 'Không thể xóa ngân hàng câu hỏi khi Đợt thi thật đang diễn ra. Hãy chờ đợt thi kết thúc hoặc điều chỉnh thời gian Thi thật.';
  end if;

  perform 1
  from public.question_sets
  where space_id = target_set.space_id
  for update;

  select count(*)
  into set_count
  from public.question_sets
  where space_id = target_set.space_id;

  if set_count <= 1 then
    raise exception 'Space phải có ít nhất 1 ngân hàng câu hỏi.';
  end if;

  select coalesce(
    jsonb_agg(item) filter (
      where coalesce(
        nullif(item ->> 'question_set_id', '')::bigint,
        nullif(item ->> 'id', '')::bigint
      ) <> target_question_set_id
    ),
    '[]'::jsonb
  )
  into remaining_config
  from jsonb_array_elements(coalesce(target_space.real_question_sets, '[]'::jsonb)) as item;

  select count(*)
  into deleted_question_count
  from public.questions
  where question_set_id = target_question_set_id;

  update public.spaces
  set real_question_sets = remaining_config,
      updated_at = now()
  where id = target_set.space_id;

  delete from public.question_sets
  where id = target_question_set_id;

  return jsonb_build_object(
    'id', target_question_set_id,
    'name', target_set.name,
    'deleted_questions', deleted_question_count
  );
end;
$$;

revoke all on function public.clear_question_set_questions(bigint) from public;
grant execute on function public.clear_question_set_questions(bigint) to authenticated;
revoke all on function public.delete_question_set_cascade(bigint) from public;
grant execute on function public.delete_question_set_cascade(bigint) to authenticated;
revoke delete on public.question_sets, public.questions from authenticated;

create or replace function public.backup_app_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_superadmin() then
    raise exception 'Only superadmin can create backups';
  end if;

  return jsonb_build_object(
    'schema_version', 1,
    'created_at', now(),
    'profiles', coalesce((select jsonb_agg(to_jsonb(t)) from public.profiles t), '[]'::jsonb),
    'spaces', coalesce((select jsonb_agg(to_jsonb(t)) from public.spaces t), '[]'::jsonb),
    'space_admins', coalesce((select jsonb_agg(to_jsonb(t)) from public.space_admins t), '[]'::jsonb),
    'groups', coalesce((select jsonb_agg(to_jsonb(t)) from public.groups t), '[]'::jsonb),
    'question_sets', coalesce((select jsonb_agg(to_jsonb(t)) from public.question_sets t), '[]'::jsonb),
    'questions', coalesce((select jsonb_agg(to_jsonb(t)) from public.questions t), '[]'::jsonb),
    'quiz_attempts', coalesce((select jsonb_agg(to_jsonb(t)) from public.quiz_attempts t), '[]'::jsonb)
  );
end;
$$;

create or replace function public.restore_app_data(payload jsonb, replace_existing boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  restored_spaces integer := 0;
  restored_groups integer := 0;
  restored_questions integer := 0;
begin
  if not public.is_superadmin() then
    raise exception 'Only superadmin can restore backups';
  end if;
  if coalesce((payload ->> 'schema_version')::integer, 0) <> 1 then
    raise exception 'Unsupported backup schema version';
  end if;

  if replace_existing then
    delete from public.spaces;
    delete from public.quiz_attempts;
  end if;

  insert into public.profiles
  select *
  from jsonb_populate_recordset(null::public.profiles, coalesce(payload -> 'profiles', '[]'::jsonb))
  on conflict (id) do update set
    email = excluded.email,
    fullname = excluded.fullname,
    role = excluded.role,
    active = excluded.active,
    updated_at = excluded.updated_at;

  insert into public.spaces
  select *
  from jsonb_populate_recordset(null::public.spaces, coalesce(payload -> 'spaces', '[]'::jsonb))
  on conflict (id) do update set
    name = excluded.name,
    slug = excluded.slug,
    timer_seconds = excluded.timer_seconds,
    exam_start_time = excluded.exam_start_time,
    allowed_late_minutes = excluded.allowed_late_minutes,
    real_exam_enabled = excluded.real_exam_enabled,
    real_question_percent = excluded.real_question_percent,
    real_timer_seconds = excluded.real_timer_seconds,
    real_multi_percent = excluded.real_multi_percent,
    real_max_attempts = excluded.real_max_attempts,
    real_scoring_method = excluded.real_scoring_method,
    real_exam_name = excluded.real_exam_name,
    real_question_sets = excluded.real_question_sets,
    mock_result_retention_days = excluded.mock_result_retention_days,
    real_result_retention_exams = excluded.real_result_retention_exams,
    real_exam_version = excluded.real_exam_version,
    real_start_at = excluded.real_start_at,
    real_end_at = excluded.real_end_at,
    published = excluded.published,
    updated_at = excluded.updated_at;
  get diagnostics restored_spaces = row_count;

  insert into public.groups
  select *
  from jsonb_populate_recordset(null::public.groups, coalesce(payload -> 'groups', '[]'::jsonb))
  on conflict (id) do update set space_id = excluded.space_id, name = excluded.name;
  get diagnostics restored_groups = row_count;

  insert into public.question_sets
  select *
  from jsonb_populate_recordset(null::public.question_sets, coalesce(payload -> 'question_sets', '[]'::jsonb))
  on conflict (id) do update set space_id = excluded.space_id, name = excluded.name;

  insert into public.questions
  select *
  from jsonb_populate_recordset(null::public.questions, coalesce(payload -> 'questions', '[]'::jsonb))
  on conflict (id) do update set
    space_id = excluded.space_id,
    question_set_id = excluded.question_set_id,
    order_no = excluded.order_no,
    type = excluded.type,
    content = excluded.content,
    options_json = excluded.options_json,
    correct_json = excluded.correct_json;
  get diagnostics restored_questions = row_count;

  insert into public.space_admins
  select *
  from jsonb_populate_recordset(null::public.space_admins, coalesce(payload -> 'space_admins', '[]'::jsonb))
  on conflict do nothing;

  insert into public.quiz_attempts
  select *
  from jsonb_populate_recordset(null::public.quiz_attempts, coalesce(payload -> 'quiz_attempts', '[]'::jsonb))
  on conflict (id) do nothing;

  perform setval(pg_get_serial_sequence('public.spaces', 'id'), coalesce((select max(id) from public.spaces), 1), true);
  perform setval(pg_get_serial_sequence('public.groups', 'id'), coalesce((select max(id) from public.groups), 1), true);
  perform setval(pg_get_serial_sequence('public.question_sets', 'id'), coalesce((select max(id) from public.question_sets), 1), true);
  perform setval(pg_get_serial_sequence('public.questions', 'id'), coalesce((select max(id) from public.questions), 1), true);

  return jsonb_build_object(
    'ok', true,
    'spaces', restored_spaces,
    'groups', restored_groups,
    'questions', restored_questions
  );
end;
$$;

revoke all on function public.backup_app_data() from public;
revoke all on function public.restore_app_data(jsonb, boolean) from public;
grant execute on function public.backup_app_data() to authenticated;
grant execute on function public.restore_app_data(jsonb, boolean) to authenticated;

create or replace function public.sync_app_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.spaces', 'id'), coalesce((select max(id) from public.spaces), 1), true);
  perform setval(pg_get_serial_sequence('public.groups', 'id'), coalesce((select max(id) from public.groups), 1), true);
  perform setval(pg_get_serial_sequence('public.question_sets', 'id'), coalesce((select max(id) from public.question_sets), 1), true);
  perform setval(pg_get_serial_sequence('public.questions', 'id'), coalesce((select max(id) from public.questions), 1), true);
end;
$$;

revoke all on function public.sync_app_sequences() from public;
grant execute on function public.sync_app_sequences() to service_role;

create or replace function public.attach_real_exam_metadata()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.mode = 'real' then
    select s.real_exam_version, s.real_exam_name, s.real_start_at, s.real_end_at
      into new.real_exam_version, new.real_exam_name, new.real_exam_start_at, new.real_exam_end_at
    from public.spaces s
    where s.slug = new.space_slug;
  else
    new.real_exam_version := null;
    new.real_exam_name := null;
    new.real_exam_start_at := null;
    new.real_exam_end_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists quiz_attempts_attach_real_exam_metadata on public.quiz_attempts;
create trigger quiz_attempts_attach_real_exam_metadata
before insert on public.quiz_attempts
for each row execute function public.attach_real_exam_metadata();

create or replace function public.cleanup_space_results_unchecked(target_space_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_slug text;
  mock_days integer;
  real_exams integer;
  deleted_mock_by_days integer := 0;
  deleted_mock_by_cap integer := 0;
  deleted_real_by_exams integer := 0;
  deleted_real_by_cap integer := 0;
begin
  select s.slug, coalesce(s.mock_result_retention_days, 7), coalesce(s.real_result_retention_exams, 7)
  into target_slug, mock_days, real_exams
  from public.spaces s
  where s.id = target_space_id;

  if target_slug is null then
    raise exception 'Space không tồn tại.';
  end if;

  delete from public.quiz_attempts qa
  where qa.space_slug = target_slug
    and qa.mode = 'mock'
    and qa.submitted_at < now() - make_interval(days => mock_days);
  get diagnostics deleted_mock_by_days = row_count;

  with old_mock as (
    select qa.id
    from public.quiz_attempts qa
    where qa.space_slug = target_slug and qa.mode = 'mock'
    order by qa.submitted_at desc
    offset 500
  )
  delete from public.quiz_attempts qa
  using old_mock om
  where qa.id = om.id;
  get diagnostics deleted_mock_by_cap = row_count;

  with ranked_exams as (
    select qa.real_exam_version, dense_rank() over (order by max(qa.submitted_at) desc) as exam_rank
    from public.quiz_attempts qa
    where qa.space_slug = target_slug
      and qa.mode = 'real'
      and qa.real_exam_version is not null
    group by qa.real_exam_version
  ),
  old_exams as (
    select re.real_exam_version from ranked_exams re where re.exam_rank > real_exams
  )
  delete from public.quiz_attempts qa
  using old_exams oe
  where qa.space_slug = target_slug
    and qa.mode = 'real'
    and qa.real_exam_version = oe.real_exam_version;
  get diagnostics deleted_real_by_exams = row_count;

  with old_real as (
    select qa.id
    from public.quiz_attempts qa
    where qa.space_slug = target_slug and qa.mode = 'real'
    order by qa.submitted_at desc
    offset 1000
  )
  delete from public.quiz_attempts qa
  using old_real orl
  where qa.id = orl.id;
  get diagnostics deleted_real_by_cap = row_count;

  return jsonb_build_object(
    'ok', true,
    'mock_deleted_by_days', deleted_mock_by_days,
    'mock_deleted_by_cap', deleted_mock_by_cap,
    'real_deleted_by_exam_limit', deleted_real_by_exams,
    'real_deleted_by_cap', deleted_real_by_cap
  );
end;
$$;

revoke all on function public.cleanup_space_results_unchecked(bigint) from public;

create or replace function public.cleanup_space_results(target_space_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.can_manage_space(target_space_id) then
    raise exception 'Không có quyền quản lý kết quả của Space này.';
  end if;
  return public.cleanup_space_results_unchecked(target_space_id);
end;
$$;

revoke all on function public.cleanup_space_results(bigint) from public;
grant execute on function public.cleanup_space_results(bigint) to authenticated;

create or replace function public.cleanup_space_results_after_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_space_id bigint;
begin
  select s.id into target_space_id
  from public.spaces s
  where s.slug = new.space_slug;

  if target_space_id is not null then
    perform public.cleanup_space_results_unchecked(target_space_id);
  end if;

  return null;
end;
$$;

drop trigger if exists quiz_attempts_cleanup_space_results on public.quiz_attempts;
create trigger quiz_attempts_cleanup_space_results
after insert on public.quiz_attempts
for each row execute function public.cleanup_space_results_after_insert();

create or replace function public.list_real_exam_periods(requested_slug text)
returns table (
  real_exam_version text,
  real_exam_name text,
  real_exam_start_at timestamptz,
  real_exam_end_at timestamptz,
  submitted_count bigint,
  latest_submitted_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_space_id bigint;
begin
  select s.id into target_space_id
  from public.spaces s
  where s.slug = requested_slug;

  if target_space_id is null or not public.can_manage_space(target_space_id) then
    raise exception 'Không có quyền xem kết quả của Space này.';
  end if;

  return query
  select
    qa.real_exam_version,
    coalesce(max(nullif(qa.real_exam_name, '')), 'Đợt thi thật chưa đặt tên') as real_exam_name,
    min(qa.real_exam_start_at) as real_exam_start_at,
    max(qa.real_exam_end_at) as real_exam_end_at,
    count(*) as submitted_count,
    max(qa.submitted_at) as latest_submitted_at
  from public.quiz_attempts qa
  where qa.space_slug = requested_slug
    and qa.mode = 'real'
    and qa.real_exam_version is not null
  group by qa.real_exam_version
  order by max(qa.submitted_at) desc;
end;
$$;

revoke all on function public.list_real_exam_periods(text) from public;
grant execute on function public.list_real_exam_periods(text) to authenticated;

create or replace function public.export_real_exam_results_by_version(
  requested_slug text,
  requested_exam_version text
)
returns table (
  group_name text,
  real_exam_name text,
  real_exam_version text,
  real_exam_start_at timestamptz,
  real_exam_end_at timestamptz,
  student_name text,
  score numeric,
  total_questions integer,
  correct_count integer,
  wrong_count integer,
  duration_seconds integer,
  started_at timestamptz,
  submitted_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_space_id bigint;
begin
  select s.id into target_space_id
  from public.spaces s
  where s.slug = requested_slug;

  if target_space_id is null or not public.can_manage_space(target_space_id) then
    raise exception 'Không có quyền xuất kết quả của Space này.';
  end if;

  return query
  with best_attempts as (
    select
      qa.*,
      row_number() over (
        partition by qa.real_exam_version, qa.student_name_key
        order by qa.score desc, qa.duration_seconds asc, qa.submitted_at desc
      ) as attempt_rank
    from public.quiz_attempts qa
    where qa.space_slug = requested_slug
      and qa.mode = 'real'
      and qa.real_exam_version = requested_exam_version
  )
  select
    ba.group_name,
    ba.real_exam_name,
    ba.real_exam_version,
    ba.real_exam_start_at,
    ba.real_exam_end_at,
    ba.student_name,
    ba.score,
    ba.total_questions,
    ba.correct_count,
    ba.wrong_count,
    ba.duration_seconds,
    ba.started_at,
    ba.submitted_at
  from best_attempts ba
  where ba.attempt_rank = 1
  order by ba.score desc, ba.duration_seconds asc, ba.submitted_at desc, ba.student_name;
end;
$$;

revoke all on function public.export_real_exam_results_by_version(text, text) from public;
grant execute on function public.export_real_exam_results_by_version(text, text) to authenticated;

notify pgrst, 'reload schema';
