begin;

create table if not exists public.real_exam_revisions (
  id bigint generated by default as identity primary key,
  real_exam_id bigint not null references public.real_exams(id) on delete restrict,
  revision_no integer not null check (revision_no > 0),
  start_at timestamptz not null,
  end_at timestamptz not null,
  question_percent integer not null check (question_percent in (30, 50, 70, 100)),
  timer_seconds integer not null check (timer_seconds in (45, 60, 90, 120)),
  multi_percent integer not null check (multi_percent in (30, 50, 70, 100)),
  max_attempts integer not null check (max_attempts between 1 and 5),
  scoring_method integer not null check (scoring_method in (1, 2)),
  source_version uuid not null,
  created_by uuid,
  created_at timestamptz not null default now(),
  unique (real_exam_id, revision_no),
  check (start_at < end_at)
);

create table if not exists public.real_exam_revision_sources (
  revision_id bigint not null references public.real_exam_revisions(id) on delete restrict,
  question_set_id bigint not null references public.question_sets(id) on delete restrict,
  question_set_name text not null,
  percent integer not null check (percent between 0 and 100),
  primary key (revision_id, question_set_id)
);

create table if not exists public.real_exam_revision_question_refs (
  revision_id bigint not null references public.real_exam_revisions(id) on delete restrict,
  question_code integer not null references public.questions(question_code) on delete restrict,
  generated_order integer not null,
  created_at timestamptz not null default now(),
  primary key (revision_id, question_code),
  unique (revision_id, generated_order)
);

alter table public.real_exams
  add column if not exists current_revision_id bigint,
  add column if not exists manual_running boolean not null default true;

alter table public.quiz_attempts
  add column if not exists real_exam_revision_id bigint;

create or replace function public.real_exam_status(exam public.real_exams)
returns text
language sql
stable
as $$
  select case
    when exam.hidden_at is not null then 'hidden'
    when exam.ended_at is not null or now() > exam.end_at then 'ended'
    when now() < exam.start_at then 'scheduled'
    when not exam.manual_running then 'paused'
    else 'active'
  end
$$;

create or replace function public.set_real_exam_running(
  target_real_exam_id bigint,
  should_run boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
begin
  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id
  for update;

  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  if target_exam.hidden_at is not null then
    raise exception 'Đợt thi thật đã được ẩn.';
  end if;
  if coalesce(should_run, false) and target_exam.end_at <= now() then
    raise exception 'Hãy điều chỉnh thời gian kết thúc Đợt thi';
  end if;

  update public.real_exams
  set manual_running = coalesce(should_run, false),
      ended_at = case
        when coalesce(should_run, false) then null
        else ended_at
      end,
      updated_at = now()
  where id = target_real_exam_id
  returning * into target_exam;

  return to_jsonb(target_exam) || jsonb_build_object(
    'status', public.real_exam_status(target_exam)
  );
end;
$$;

create or replace function public.archive_real_exam_revision_unchecked(
  target_real_exam_id bigint,
  target_revision_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.real_exam_revision_question_refs
  where revision_id = target_revision_id;

  insert into public.real_exam_revision_question_refs(
    revision_id,
    question_code,
    generated_order,
    created_at
  )
  select
    target_revision_id,
    ref.question_code,
    ref.generated_order,
    ref.created_at
  from public.real_exam_question_refs ref
  where ref.real_exam_id = target_real_exam_id;
end;
$$;

create or replace function public.create_real_exam_revision_unchecked(target_real_exam_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
  next_revision_no integer;
  created_revision_id bigint;
begin
  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id
  for update;

  if not found then
    raise exception 'Đợt thi thật không tồn tại.';
  end if;

  select coalesce(max(revision_no), 0) + 1
  into next_revision_no
  from public.real_exam_revisions
  where real_exam_id = target_real_exam_id;

  insert into public.real_exam_revisions(
    real_exam_id,
    revision_no,
    start_at,
    end_at,
    question_percent,
    timer_seconds,
    multi_percent,
    max_attempts,
    scoring_method,
    source_version,
    created_by
  )
  values (
    target_exam.id,
    next_revision_no,
    target_exam.start_at,
    target_exam.end_at,
    target_exam.question_percent,
    target_exam.timer_seconds,
    target_exam.multi_percent,
    target_exam.max_attempts,
    target_exam.scoring_method,
    target_exam.source_version,
    auth.uid()
  )
  returning id into created_revision_id;

  insert into public.real_exam_revision_sources(
    revision_id,
    question_set_id,
    question_set_name,
    percent
  )
  select
    created_revision_id,
    source.question_set_id,
    source.question_set_name,
    source.percent
  from public.real_exam_sources source
  where source.real_exam_id = target_real_exam_id;

  perform public.archive_real_exam_revision_unchecked(
    target_real_exam_id,
    created_revision_id
  );

  update public.real_exams
  set current_revision_id = created_revision_id,
      updated_at = now()
  where id = target_real_exam_id;

  return created_revision_id;
end;
$$;

do $$
declare
  exam_row record;
  revision_id bigint;
begin
  for exam_row in
    select exam.id, exam.current_revision_id
    from public.real_exams exam
    order by exam.id
  loop
    if exam_row.current_revision_id is null then
      select revision.id
      into revision_id
      from public.real_exam_revisions revision
      where revision.real_exam_id = exam_row.id
      order by revision.revision_no desc
      limit 1;

      if revision_id is null then
        revision_id := public.create_real_exam_revision_unchecked(exam_row.id);
      else
        update public.real_exams
        set current_revision_id = revision_id
        where id = exam_row.id;
        perform public.archive_real_exam_revision_unchecked(exam_row.id, revision_id);
      end if;
    end if;
  end loop;
end;
$$;

update public.quiz_attempts attempt
set real_exam_revision_id = exam.current_revision_id
from public.real_exams exam
where attempt.real_exam_id = exam.id
  and attempt.real_exam_revision_id is null;

alter table public.real_exams
  drop constraint if exists real_exams_current_revision_id_fkey;
alter table public.real_exams
  add constraint real_exams_current_revision_id_fkey
  foreign key (current_revision_id)
  references public.real_exam_revisions(id)
  on delete restrict;

alter table public.quiz_attempts
  drop constraint if exists quiz_attempts_real_exam_revision_id_fkey;
alter table public.quiz_attempts
  add constraint quiz_attempts_real_exam_revision_id_fkey
  foreign key (real_exam_revision_id)
  references public.real_exam_revisions(id)
  on delete restrict;

create index if not exists real_exam_revisions_exam_idx
on public.real_exam_revisions(real_exam_id, revision_no desc);

create index if not exists quiz_attempts_real_exam_revision_idx
on public.quiz_attempts(real_exam_revision_id, submitted_at desc);

create or replace function public.protect_snapshotted_question()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (
    exists (
      select 1
      from public.real_exam_question_refs ref
      where ref.question_code = old.question_code
    )
    or exists (
      select 1
      from public.real_exam_revision_question_refs ref
      where ref.question_code = old.question_code
    )
  ) and (
    new.type is distinct from old.type
    or new.content is distinct from old.content
    or new.options_json is distinct from old.options_json
    or new.correct_json is distinct from old.correct_json
  ) then
    raise exception 'Câu hỏi #% đã thuộc Đề thi của một Đợt thi thật. Hãy tạo câu hỏi mới thay vì sửa nội dung.', old.question_code;
  end if;
  return new;
end;
$$;

create or replace function public.create_real_exam(target_space_id bigint, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created_exam public.real_exams%rowtype;
  allocated_code integer;
  generated_count integer;
  created_revision_id bigint;
  created_revision_no integer;
  start_value timestamptz;
  end_value timestamptz;
begin
  if not public.can_manage_space(target_space_id) then
    raise exception 'Bạn không có quyền quản lý Space này.';
  end if;

  start_value := nullif(payload ->> 'start_at', '')::timestamptz;
  end_value := nullif(payload ->> 'end_at', '')::timestamptz;
  if start_value is null or end_value is null or start_value >= end_value then
    raise exception 'Khoảng thời gian Thi thật không hợp lệ.';
  end if;

  allocated_code := public.allocate_real_exam_code();
  insert into public.real_exams(
    code, space_id, name, start_at, end_at, question_percent, timer_seconds,
    multi_percent, max_attempts, scoring_method, created_by
  )
  values (
    allocated_code,
    target_space_id,
    nullif(trim(payload ->> 'name'), ''),
    start_value,
    end_value,
    coalesce((payload ->> 'question_percent')::integer, 50),
    coalesce((payload ->> 'timer_seconds')::integer, 60),
    coalesce((payload ->> 'multi_percent')::integer, 50),
    coalesce((payload ->> 'max_attempts')::integer, 1),
    coalesce((payload ->> 'scoring_method')::integer, 2),
    auth.uid()
  )
  returning * into created_exam;

  if created_exam.name is null then
    raise exception 'Tên Đợt thi thật là bắt buộc.';
  end if;

  perform public.replace_real_exam_sources(created_exam.id, payload -> 'sources');
  generated_count := public.generate_real_exam_snapshot_unchecked(created_exam.id);
  created_revision_id := public.create_real_exam_revision_unchecked(created_exam.id);

  select revision_no
  into created_revision_no
  from public.real_exam_revisions
  where id = created_revision_id;

  return to_jsonb(created_exam) || jsonb_build_object(
    'current_revision_id', created_revision_id,
    'current_revision_no', created_revision_no,
    'question_count', generated_count,
    'share_path', '/exam/' || created_exam.code::text
  );
end;
$$;

create or replace function public.update_real_exam(target_real_exam_id bigint, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
  generated_count integer;
  created_revision_id bigint;
  created_revision_no integer;
  start_value timestamptz;
  end_value timestamptz;
begin
  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id
  for update;

  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  if target_exam.hidden_at is not null then
    raise exception 'Đợt thi thật đã được ẩn.';
  end if;

  start_value := nullif(payload ->> 'start_at', '')::timestamptz;
  end_value := nullif(payload ->> 'end_at', '')::timestamptz;
  if start_value is null or end_value is null or start_value >= end_value then
    raise exception 'Khoảng thời gian Thi thật không hợp lệ.';
  end if;
  if not (payload ? 'sources') then
    raise exception 'Nguồn câu hỏi là bắt buộc khi tạo phiên bản mới.';
  end if;

  update public.real_exams
  set name = coalesce(nullif(trim(payload ->> 'name'), ''), name),
      start_at = start_value,
      end_at = end_value,
      ended_at = null,
      question_percent = coalesce((payload ->> 'question_percent')::integer, question_percent),
      timer_seconds = coalesce((payload ->> 'timer_seconds')::integer, timer_seconds),
      multi_percent = coalesce((payload ->> 'multi_percent')::integer, multi_percent),
      max_attempts = coalesce((payload ->> 'max_attempts')::integer, max_attempts),
      scoring_method = coalesce((payload ->> 'scoring_method')::integer, scoring_method),
      updated_at = now()
  where id = target_real_exam_id
  returning * into target_exam;

  perform public.replace_real_exam_sources(target_real_exam_id, payload -> 'sources');
  generated_count := public.generate_real_exam_snapshot_unchecked(target_real_exam_id);
  created_revision_id := public.create_real_exam_revision_unchecked(target_real_exam_id);

  select revision_no
  into created_revision_no
  from public.real_exam_revisions
  where id = created_revision_id;

  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id;

  return to_jsonb(target_exam) || jsonb_build_object(
    'current_revision_id', created_revision_id,
    'current_revision_no', created_revision_no,
    'question_count', generated_count,
    'created_new_revision', true
  );
end;
$$;

create or replace function public.regenerate_real_exam_snapshot(target_real_exam_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
  generated_count integer;
  created_revision_id bigint;
  created_revision_no integer;
begin
  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id
  for update;

  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  if target_exam.hidden_at is not null
     or public.real_exam_status(target_exam) <> 'scheduled' then
    raise exception 'Chỉ có thể tạo lại nguồn khi Đợt thi đang ở trạng thái Sắp diễn ra.';
  end if;

  generated_count := public.generate_real_exam_snapshot_unchecked(target_real_exam_id);
  created_revision_id := public.create_real_exam_revision_unchecked(target_real_exam_id);

  select revision_no
  into created_revision_no
  from public.real_exam_revisions
  where id = created_revision_id;

  return jsonb_build_object(
    'id', target_real_exam_id,
    'current_revision_id', created_revision_id,
    'current_revision_no', created_revision_no,
    'question_count', generated_count
  );
end;
$$;

create or replace function public.get_real_exam_admin(target_real_exam_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
begin
  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id;

  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;

  return to_jsonb(target_exam) || jsonb_build_object(
    'status', public.real_exam_status(target_exam),
    'current_revision_no', (
      select revision.revision_no
      from public.real_exam_revisions revision
      where revision.id = target_exam.current_revision_id
    ),
    'question_count', (
      select count(*)
      from public.real_exam_question_refs
      where real_exam_id = target_real_exam_id
    ),
    'result_count', (
      select count(*)
      from public.quiz_attempts
      where real_exam_id = target_real_exam_id
    ),
    'sources', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', source.question_set_id,
        'name', source.question_set_name,
        'percent', source.percent
      ) order by source.question_set_name)
      from public.real_exam_sources source
      where source.real_exam_id = target_real_exam_id
    ), '[]'::jsonb),
    'revisions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', revision.id,
        'revision_no', revision.revision_no,
        'start_at', revision.start_at,
        'end_at', revision.end_at,
        'question_count', (
          select count(*)
          from public.real_exam_revision_question_refs ref
          where ref.revision_id = revision.id
        ),
        'result_count', (
          select count(*)
          from public.quiz_attempts attempt
          where attempt.real_exam_revision_id = revision.id
        )
      ) order by revision.revision_no desc)
      from public.real_exam_revisions revision
      where revision.real_exam_id = target_real_exam_id
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.get_real_exam_public(requested_code integer)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
  target_space public.spaces%rowtype;
  revision_no integer;
begin
  select *
  into target_exam
  from public.real_exams
  where code = requested_code
    and hidden_at is null;

  if not found then
    return jsonb_build_object('exists', false);
  end if;

  select *
  into target_space
  from public.spaces
  where id = target_exam.space_id;

  if not target_space.published then
    return jsonb_build_object('exists', false);
  end if;

  select revision.revision_no
  into revision_no
  from public.real_exam_revisions revision
  where revision.id = target_exam.current_revision_id;

  return jsonb_build_object(
    'exists', true,
    'id', target_exam.id,
    'code', target_exam.code,
    'name', target_exam.name,
    'status', public.real_exam_status(target_exam),
    'start_at', target_exam.start_at,
    'end_at', target_exam.end_at,
    'manual_running', target_exam.manual_running,
    'timer_seconds', target_exam.timer_seconds,
    'max_attempts', target_exam.max_attempts,
    'scoring_method', target_exam.scoring_method,
    'revision_id', target_exam.current_revision_id,
    'revision_no', revision_no,
    'space', jsonb_build_object(
      'id', target_space.id,
      'slug', target_space.slug,
      'name', target_space.name,
      'groups', coalesce((
        select jsonb_agg(group_row.name order by group_row.name)
        from public.groups group_row
        where group_row.space_id = target_space.id
      ), '[]'::jsonb)
    ),
    'questions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', question.question_code,
        'question_code', question.question_code,
        'type', question.type,
        'content', question.content,
        'options_json', question.options_json,
        'order_no', ref.generated_order
      ) order by ref.generated_order)
      from public.real_exam_question_refs ref
      join public.questions question
        on question.question_code = ref.question_code
      where ref.real_exam_id = target_exam.id
        and public.real_exam_status(target_exam) = 'active'
    ), '[]'::jsonb)
  );
end;
$$;

drop function if exists public.list_real_exam_results(bigint, integer);

create or replace function public.list_real_exam_results(
  target_real_exam_id bigint,
  result_limit integer default 20,
  target_revision_id bigint default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
begin
  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id;

  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền xem kết quả Đợt thi thật này.';
  end if;

  if target_revision_id is not null and not exists (
    select 1
    from public.real_exam_revisions revision
    where revision.id = target_revision_id
      and revision.real_exam_id = target_real_exam_id
  ) then
    raise exception 'Phiên bản Đợt thi không hợp lệ.';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(result_row) order by result_row.submitted_at desc)
    from (
      select
        attempt.id,
        target_exam.code as real_exam_code,
        target_exam.name as real_exam_name,
        attempt.real_exam_revision_id,
        revision.revision_no as real_exam_revision_no,
        attempt.group_name,
        attempt.student_name,
        attempt.score,
        attempt.total_questions,
        attempt.correct_count,
        attempt.wrong_count,
        attempt.duration_seconds,
        attempt.started_at,
        attempt.submitted_at
      from public.quiz_attempts attempt
      left join public.real_exam_revisions revision
        on revision.id = attempt.real_exam_revision_id
      where attempt.real_exam_id = target_real_exam_id
        and (
          target_revision_id is null
          or attempt.real_exam_revision_id = target_revision_id
        )
      order by attempt.submitted_at desc
      limit least(5000, greatest(1, coalesce(result_limit, 20)))
    ) result_row
  ), '[]'::jsonb);
end;
$$;

create or replace function public.get_real_exam_attempt_count(
  requested_code integer,
  requested_student_name text
)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer
  from public.quiz_attempts attempt
  join public.real_exams exam
    on exam.id = attempt.real_exam_id
  where exam.code = requested_code
    and attempt.mode = 'real'
    and attempt.real_exam_revision_id = exam.current_revision_id
    and attempt.student_name_key = lower(trim(regexp_replace(
      coalesce(requested_student_name, ''),
      '\s+',
      ' ',
      'g'
    )))
$$;

create or replace function public.attach_real_exam_metadata()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_max_attempts integer;
  target_ended_at timestamptz;
  target_manual_running boolean;
begin
  if new.mode = 'real' and new.real_exam_code is not null then
    select
      exam.id,
      exam.code,
      exam.current_revision_id,
      exam.legacy_version,
      exam.name,
      exam.start_at,
      exam.end_at,
      exam.max_attempts,
      exam.ended_at,
      exam.manual_running
    into
      new.real_exam_id,
      new.real_exam_code,
      new.real_exam_revision_id,
      new.real_exam_version,
      new.real_exam_name,
      new.real_exam_start_at,
      new.real_exam_end_at,
      target_max_attempts,
      target_ended_at,
      target_manual_running
    from public.real_exams exam
    where exam.code = new.real_exam_code
      and exam.hidden_at is null;

    if new.real_exam_id is null then
      raise exception 'Đợt thi thật không tồn tại.';
    end if;
    if not target_manual_running then
      raise exception 'Đợt thi đã tạm dừng.';
    end if;
    if new.started_at < new.real_exam_start_at
       or new.started_at > new.real_exam_end_at
       or (target_ended_at is not null and new.started_at > target_ended_at) then
      raise exception 'Lượt thi không bắt đầu trong thời gian Đợt thi thật.';
    end if;
    if (
      select count(*)
      from public.quiz_attempts attempt
      where attempt.real_exam_revision_id = new.real_exam_revision_id
        and attempt.student_name_key = new.student_name_key
    ) >= target_max_attempts then
      raise exception 'Học viên đã hết số lượt Thi thật của phiên bản hiện tại.';
    end if;
  elsif new.mode = 'real' then
    select
      space.real_exam_version,
      space.real_exam_name,
      space.real_start_at,
      space.real_end_at
    into
      new.real_exam_version,
      new.real_exam_name,
      new.real_exam_start_at,
      new.real_exam_end_at
    from public.spaces space
    where space.slug = new.space_slug;
  else
    new.real_exam_id := null;
    new.real_exam_code := null;
    new.real_exam_revision_id := null;
    new.real_exam_version := null;
    new.real_exam_name := null;
    new.real_exam_start_at := null;
    new.real_exam_end_at := null;
  end if;
  return new;
end;
$$;

drop function if exists public.hide_real_exam(bigint);

create or replace function public.hide_real_exam(
  target_real_exam_id bigint,
  confirmation_code integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
begin
  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id
  for update;

  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  if target_exam.ended_at is null and now() <= target_exam.end_at then
    raise exception 'Chỉ có thể ẩn Đợt thi thật đã kết thúc.';
  end if;
  if confirmation_code is distinct from target_exam.code then
    raise exception 'Mã xác nhận Đợt thi không chính xác.';
  end if;

  update public.real_exams
  set hidden_at = now(),
      hidden_by = auth.uid(),
      updated_at = now()
  where id = target_real_exam_id
  returning * into target_exam;

  return to_jsonb(target_exam);
end;
$$;

alter table public.real_exam_revisions enable row level security;
alter table public.real_exam_revision_sources enable row level security;
alter table public.real_exam_revision_question_refs enable row level security;

drop policy if exists "real exam revisions admins read" on public.real_exam_revisions;
create policy "real exam revisions admins read"
on public.real_exam_revisions for select to authenticated
using (
  exists (
    select 1
    from public.real_exams exam
    where exam.id = real_exam_id
      and public.can_manage_space(exam.space_id)
  )
);

drop policy if exists "real exam revision sources admins read" on public.real_exam_revision_sources;
create policy "real exam revision sources admins read"
on public.real_exam_revision_sources for select to authenticated
using (
  exists (
    select 1
    from public.real_exam_revisions revision
    join public.real_exams exam
      on exam.id = revision.real_exam_id
    where revision.id = revision_id
      and public.can_manage_space(exam.space_id)
  )
);

drop policy if exists "real exam revision refs admins read" on public.real_exam_revision_question_refs;
create policy "real exam revision refs admins read"
on public.real_exam_revision_question_refs for select to authenticated
using (
  exists (
    select 1
    from public.real_exam_revisions revision
    join public.real_exams exam
      on exam.id = revision.real_exam_id
    where revision.id = revision_id
      and public.can_manage_space(exam.space_id)
  )
);

revoke all on public.real_exam_revisions,
  public.real_exam_revision_sources,
  public.real_exam_revision_question_refs
from anon;

grant select on public.real_exam_revisions,
  public.real_exam_revision_sources,
  public.real_exam_revision_question_refs
to authenticated;

revoke all on function public.archive_real_exam_revision_unchecked(bigint, bigint) from public;
revoke all on function public.create_real_exam_revision_unchecked(bigint) from public;

revoke all on function public.set_real_exam_running(bigint, boolean) from public;
grant execute on function public.set_real_exam_running(bigint, boolean) to authenticated;

revoke all on function public.list_real_exam_results(bigint, integer, bigint) from public;
grant execute on function public.list_real_exam_results(bigint, integer, bigint) to authenticated;

revoke all on function public.hide_real_exam(bigint, integer) from public;
grant execute on function public.hide_real_exam(bigint, integer) to authenticated;

notify pgrst, 'reload schema';

commit;
