begin;

create extension if not exists pgcrypto;

create table if not exists public.question_code_registry (
  code integer primary key check (code between 10000000 and 99999999),
  question_id bigint unique,
  allocated_at timestamptz not null default now()
);

alter table public.questions
  add column if not exists question_code integer,
  add column if not exists hidden_at timestamptz,
  add column if not exists hidden_by uuid;

alter table public.question_sets
  add column if not exists hidden_at timestamptz,
  add column if not exists hidden_by uuid;

alter table public.question_sets
  drop constraint if exists question_sets_space_id_name_key;

create unique index if not exists question_sets_active_name_uidx
on public.question_sets(space_id, name)
where hidden_at is null;

create or replace function public.allocate_question_code(target_question_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate integer;
  inserted_count integer;
begin
  for attempt in 1..500 loop
    candidate := 10000000 + floor(random() * 90000000)::integer;
    insert into public.question_code_registry(code, question_id)
    values (candidate, target_question_id)
    on conflict do nothing;
    get diagnostics inserted_count = row_count;
    if inserted_count = 1 then
      return candidate;
    end if;
  end loop;
  raise exception 'Không thể cấp mã câu hỏi duy nhất. Hãy thử lại.';
end;
$$;

do $$
declare
  question_row record;
  allocated_code integer;
begin
  for question_row in
    select q.id, q.question_code
    from public.questions q
    order by q.id
  loop
    if question_row.question_code is null then
      allocated_code := public.allocate_question_code(question_row.id);
      update public.questions
      set question_code = allocated_code
      where id = question_row.id;
    else
      insert into public.question_code_registry(code, question_id)
      values (question_row.question_code, question_row.id)
      on conflict (code) do update set question_id = excluded.question_id;
    end if;
  end loop;
end;
$$;

create unique index if not exists questions_question_code_uidx
on public.questions(question_code);

alter table public.questions
  alter column question_code set not null;

create or replace function public.assign_question_code()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.question_code is null then
    new.question_code := public.allocate_question_code(new.id);
  else
    insert into public.question_code_registry(code, question_id)
    values (new.question_code, new.id)
    on conflict (code) do nothing;
    if not found then
      raise exception 'Mã câu hỏi % đã được sử dụng.', new.question_code;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists questions_assign_permanent_code on public.questions;
create trigger questions_assign_permanent_code
before insert on public.questions
for each row execute function public.assign_question_code();

create table if not exists public.real_exam_code_registry (
  code integer primary key check (code between 10000 and 99999),
  allocated_at timestamptz not null default now()
);

create table if not exists public.real_exams (
  id bigint generated by default as identity primary key,
  code integer not null unique references public.real_exam_code_registry(code) on delete restrict,
  space_id bigint not null references public.spaces(id) on delete restrict,
  name text not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  ended_at timestamptz,
  hidden_at timestamptz,
  hidden_by uuid,
  question_percent integer not null default 50 check (question_percent in (30, 50, 70, 100)),
  timer_seconds integer not null default 60 check (timer_seconds in (45, 60, 90, 120)),
  multi_percent integer not null default 50 check (multi_percent in (30, 50, 70, 100)),
  max_attempts integer not null default 1 check (max_attempts between 1 and 5),
  scoring_method integer not null default 2 check (scoring_method in (1, 2)),
  questions_generated_at timestamptz,
  source_version uuid not null default gen_random_uuid(),
  legacy_version text unique,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (start_at < end_at)
);

create index if not exists real_exams_space_status_idx
on public.real_exams(space_id, hidden_at, start_at desc, end_at desc);

create table if not exists public.real_exam_sources (
  real_exam_id bigint not null references public.real_exams(id) on delete cascade,
  question_set_id bigint references public.question_sets(id) on delete restrict,
  question_set_name text not null,
  percent integer not null check (percent between 0 and 100),
  primary key (real_exam_id, question_set_id)
);

create table if not exists public.real_exam_question_refs (
  real_exam_id bigint not null references public.real_exams(id) on delete cascade,
  question_code integer not null references public.questions(question_code) on delete restrict,
  generated_order integer not null,
  created_at timestamptz not null default now(),
  primary key (real_exam_id, question_code),
  unique (real_exam_id, generated_order)
);

create or replace function public.protect_snapshotted_question()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.real_exam_question_refs ref
    where ref.question_code = old.question_code
  ) and (
    new.type is distinct from old.type
    or new.content is distinct from old.content
    or new.options_json is distinct from old.options_json
    or new.correct_json is distinct from old.correct_json
  ) then
    raise exception 'Câu hỏi #% đã thuộc snapshot Đợt thi thật. Hãy tạo câu hỏi mới thay vì sửa nội dung.', old.question_code;
  end if;
  return new;
end;
$$;

drop trigger if exists questions_protect_snapshotted_content on public.questions;
create trigger questions_protect_snapshotted_content
before update of type, content, options_json, correct_json on public.questions
for each row execute function public.protect_snapshotted_question();

alter table public.quiz_attempts
  add column if not exists real_exam_id bigint references public.real_exams(id) on delete restrict,
  add column if not exists real_exam_code integer;

create index if not exists quiz_attempts_real_exam_id_idx
on public.quiz_attempts(real_exam_id, submitted_at desc);

create or replace function public.allocate_real_exam_code()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate integer;
  inserted_count integer;
begin
  for attempt in 1..500 loop
    candidate := 10000 + floor(random() * 90000)::integer;
    insert into public.real_exam_code_registry(code)
    values (candidate)
    on conflict do nothing;
    get diagnostics inserted_count = row_count;
    if inserted_count = 1 then
      return candidate;
    end if;
  end loop;
  raise exception 'Không thể cấp mã Đợt thi thật duy nhất. Hãy thử lại.';
end;
$$;

create or replace function public.real_exam_status(exam public.real_exams)
returns text
language sql
stable
as $$
  select case
    when exam.hidden_at is not null then 'hidden'
    when exam.ended_at is not null or now() > exam.end_at then 'ended'
    when now() < exam.start_at then 'scheduled'
    else 'active'
  end
$$;

create or replace function public.generate_real_exam_snapshot_unchecked(target_real_exam_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
  source_row record;
  source_count integer;
  source_index integer := 0;
  candidate_count integer;
  target_count integer;
  source_quota integer;
  target_multi integer;
  inserted_count integer;
  selected_count integer;
  remaining_count integer;
  current_multi integer;
  available_multi integer;
  available_single integer;
  swap_count integer;
begin
  select *
  into target_exam
  from public.real_exams
  where id = target_real_exam_id
  for update;

  if not found then
    raise exception 'Đợt thi thật không tồn tại.';
  end if;

  select count(*)
  into source_count
  from public.real_exam_sources
  where real_exam_id = target_real_exam_id and percent > 0;

  if source_count = 0 then
    raise exception 'Chọn ít nhất một Ngân hàng câu hỏi.';
  end if;

  select count(*)
  into candidate_count
  from public.questions q
  join public.real_exam_sources rs
    on rs.real_exam_id = target_real_exam_id
   and rs.question_set_id = q.question_set_id
  where q.hidden_at is null
    and rs.percent > 0;

  if candidate_count = 0 then
    raise exception 'Nguồn câu hỏi chưa có câu hỏi khả dụng.';
  end if;

  target_count := greatest(1, round(candidate_count * target_exam.question_percent / 100.0)::integer);
  target_multi := round(target_count * target_exam.multi_percent / 100.0)::integer;

  drop table if exists pg_temp.real_exam_selected_questions;
  create temporary table real_exam_selected_questions (
    question_code integer primary key,
    type text not null
  ) on commit drop;

  remaining_count := target_count;
  for source_row in
    select rs.question_set_id, rs.percent
    from public.real_exam_sources rs
    where rs.real_exam_id = target_real_exam_id and rs.percent > 0
    order by rs.question_set_id
  loop
    source_index := source_index + 1;
    source_quota := case
      when source_index = source_count then remaining_count
      else least(remaining_count, round(target_count * source_row.percent / 100.0)::integer)
    end;

    insert into real_exam_selected_questions(question_code, type)
    select q.question_code, q.type
    from public.questions q
    where q.question_set_id = source_row.question_set_id
      and q.hidden_at is null
      and q.type = 'multi'
      and not exists (
        select 1 from real_exam_selected_questions selected
        where selected.question_code = q.question_code
      )
    order by random()
    limit least(source_quota, round(source_quota * target_exam.multi_percent / 100.0)::integer);

    select count(*) into selected_count
    from real_exam_selected_questions selected
    join public.questions q on q.question_code = selected.question_code
    where q.question_set_id = source_row.question_set_id;

    insert into real_exam_selected_questions(question_code, type)
    select q.question_code, q.type
    from public.questions q
    where q.question_set_id = source_row.question_set_id
      and q.hidden_at is null
      and q.type = 'single'
      and not exists (
        select 1 from real_exam_selected_questions selected
        where selected.question_code = q.question_code
      )
    order by random()
    limit greatest(0, source_quota - selected_count);

    select count(*) into selected_count
    from real_exam_selected_questions selected
    join public.questions q on q.question_code = selected.question_code
    where q.question_set_id = source_row.question_set_id;

    insert into real_exam_selected_questions(question_code, type)
    select q.question_code, q.type
    from public.questions q
    where q.question_set_id = source_row.question_set_id
      and q.hidden_at is null
      and not exists (
        select 1 from real_exam_selected_questions selected
        where selected.question_code = q.question_code
      )
    order by random()
    limit greatest(0, source_quota - selected_count);

    select count(*) into inserted_count
    from real_exam_selected_questions selected
    join public.questions q on q.question_code = selected.question_code
    where q.question_set_id = source_row.question_set_id;
    remaining_count := greatest(0, remaining_count - inserted_count);
  end loop;

  select count(*) into selected_count from real_exam_selected_questions;
  if selected_count < target_count then
    insert into real_exam_selected_questions(question_code, type)
    select q.question_code, q.type
    from public.questions q
    join public.real_exam_sources rs
      on rs.real_exam_id = target_real_exam_id
     and rs.question_set_id = q.question_set_id
    where q.hidden_at is null
      and not exists (
        select 1 from real_exam_selected_questions selected
        where selected.question_code = q.question_code
      )
    order by
      case when q.type = 'multi'
        and (select count(*) from real_exam_selected_questions where type = 'multi') < target_multi
        then 0 else 1 end,
      random()
    limit target_count - selected_count;
  end if;

  -- Source percentages determine the first allocation. Correct the final
  -- snapshot globally so Y is a percentage of X, while allowing single
  -- questions to replace a genuine shortage of multi-answer questions.
  select count(*) into current_multi
  from real_exam_selected_questions
  where type = 'multi';

  select count(*) into available_multi
  from public.questions q
  join public.real_exam_sources rs
    on rs.real_exam_id = target_real_exam_id
   and rs.question_set_id = q.question_set_id
  where q.hidden_at is null
    and q.type = 'multi'
    and rs.percent > 0;

  swap_count := least(
    greatest(0, target_multi - current_multi),
    greatest(0, available_multi - current_multi)
  );

  if swap_count > 0 then
    delete from real_exam_selected_questions
    where question_code in (
      select selected.question_code
      from real_exam_selected_questions selected
      where selected.type = 'single'
      order by random()
      limit swap_count
    );

    insert into real_exam_selected_questions(question_code, type)
    select q.question_code, q.type
    from public.questions q
    join public.real_exam_sources rs
      on rs.real_exam_id = target_real_exam_id
     and rs.question_set_id = q.question_set_id
    where q.hidden_at is null
      and q.type = 'multi'
      and rs.percent > 0
      and not exists (
        select 1
        from real_exam_selected_questions selected
        where selected.question_code = q.question_code
      )
    order by random()
    limit swap_count;
  end if;

  select count(*) into current_multi
  from real_exam_selected_questions
  where type = 'multi';

  select count(*) into available_single
  from public.questions q
  join public.real_exam_sources rs
    on rs.real_exam_id = target_real_exam_id
   and rs.question_set_id = q.question_set_id
  where q.hidden_at is null
    and q.type = 'single'
    and rs.percent > 0;

  swap_count := least(
    greatest(0, current_multi - target_multi),
    greatest(
      0,
      available_single - (
        select count(*)
        from real_exam_selected_questions
        where type = 'single'
      )
    )
  );

  if swap_count > 0 then
    delete from real_exam_selected_questions
    where question_code in (
      select selected.question_code
      from real_exam_selected_questions selected
      where selected.type = 'multi'
      order by random()
      limit swap_count
    );

    insert into real_exam_selected_questions(question_code, type)
    select q.question_code, q.type
    from public.questions q
    join public.real_exam_sources rs
      on rs.real_exam_id = target_real_exam_id
     and rs.question_set_id = q.question_set_id
    where q.hidden_at is null
      and q.type = 'single'
      and rs.percent > 0
      and not exists (
        select 1
        from real_exam_selected_questions selected
        where selected.question_code = q.question_code
      )
    order by random()
    limit swap_count;
  end if;

  select count(*) into selected_count from real_exam_selected_questions;
  if selected_count < target_count then
    raise exception 'Nguồn câu hỏi chỉ đáp ứng %/% câu cần thiết.', selected_count, target_count;
  end if;

  delete from public.real_exam_question_refs
  where real_exam_id = target_real_exam_id;

  insert into public.real_exam_question_refs(real_exam_id, question_code, generated_order)
  select target_real_exam_id, selected.question_code, row_number() over (order by random())::integer
  from real_exam_selected_questions selected;

  update public.real_exams
  set questions_generated_at = now(),
      source_version = gen_random_uuid(),
      updated_at = now()
  where id = target_real_exam_id;

  return selected_count;
end;
$$;

create or replace function public.replace_real_exam_sources(target_real_exam_id bigint, sources jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  source_total integer;
  source_count integer;
begin
  delete from public.real_exam_sources where real_exam_id = target_real_exam_id;

  insert into public.real_exam_sources(real_exam_id, question_set_id, question_set_name, percent)
  select
    target_real_exam_id,
    qs.id,
    qs.name,
    greatest(0, least(100, coalesce((item ->> 'percent')::integer, 0)))
  from jsonb_array_elements(coalesce(sources, '[]'::jsonb)) item
  join public.real_exams exam on exam.id = target_real_exam_id
  join public.question_sets qs
    on qs.id = coalesce(nullif(item ->> 'id', '')::bigint, nullif(item ->> 'question_set_id', '')::bigint)
   and qs.space_id = exam.space_id
   and qs.hidden_at is null;

  select count(*), coalesce(sum(percent), 0)
  into source_count, source_total
  from public.real_exam_sources
  where real_exam_id = target_real_exam_id;

  if source_count = 0 or source_total <> 100 then
    raise exception 'Nguồn câu hỏi phải có ít nhất một ngân hàng và tổng tỷ lệ bằng 100%%.';
  end if;
end;
$$;

create or replace function public.create_real_exam(target_space_id bigint, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created_exam public.real_exams%rowtype;
  allocated_code integer;
  generated_count integer;
  start_value timestamptz;
  end_value timestamptz;
begin
  if not public.can_manage_space(target_space_id) then
    raise exception 'Bạn không có quyền quản lý Space này.';
  end if;

  start_value := nullif(payload ->> 'start_at', '')::timestamptz;
  end_value := nullif(payload ->> 'end_at', '')::timestamptz;
  if start_value is null or end_value is null or start_value >= end_value then
    raise exception 'Khoảng thời gian Thi thật không hợp lệ.';
  end if;

  allocated_code := public.allocate_real_exam_code();
  insert into public.real_exams(
    code, space_id, name, start_at, end_at, question_percent, timer_seconds,
    multi_percent, max_attempts, scoring_method, created_by
  )
  values (
    allocated_code,
    target_space_id,
    nullif(trim(payload ->> 'name'), ''),
    start_value,
    end_value,
    coalesce((payload ->> 'question_percent')::integer, 50),
    coalesce((payload ->> 'timer_seconds')::integer, 60),
    coalesce((payload ->> 'multi_percent')::integer, 50),
    coalesce((payload ->> 'max_attempts')::integer, 1),
    coalesce((payload ->> 'scoring_method')::integer, 2),
    auth.uid()
  )
  returning * into created_exam;

  if created_exam.name is null then
    raise exception 'Tên Đợt thi thật là bắt buộc.';
  end if;

  perform public.replace_real_exam_sources(created_exam.id, payload -> 'sources');
  generated_count := public.generate_real_exam_snapshot_unchecked(created_exam.id);

  return to_jsonb(created_exam) || jsonb_build_object(
    'question_count', generated_count,
    'share_path', '/exam/' || created_exam.code::text
  );
end;
$$;

create or replace function public.update_real_exam(target_real_exam_id bigint, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
  generated_count integer;
  has_results boolean;
  start_value timestamptz;
  end_value timestamptz;
begin
  select * into target_exam
  from public.real_exams
  where id = target_real_exam_id
  for update;

  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  if target_exam.hidden_at is not null then
    raise exception 'Đợt thi thật đã được ẩn.';
  end if;

  select exists(select 1 from public.quiz_attempts where real_exam_id = target_real_exam_id)
  into has_results;

  if target_exam.ended_at is not null or now() > target_exam.end_at then
    update public.real_exams
    set name = coalesce(nullif(trim(payload ->> 'name'), ''), name),
        updated_at = now()
    where id = target_real_exam_id
    returning * into target_exam;
    return to_jsonb(target_exam) || jsonb_build_object(
      'question_count', (select count(*) from public.real_exam_question_refs where real_exam_id = target_real_exam_id)
    );
  end if;

  if now() >= target_exam.start_at or has_results then
    raise exception 'Không thể thay đổi cấu hình sau khi cuộc thi bắt đầu hoặc đã có kết quả.';
  end if;

  start_value := coalesce(nullif(payload ->> 'start_at', '')::timestamptz, target_exam.start_at);
  end_value := coalesce(nullif(payload ->> 'end_at', '')::timestamptz, target_exam.end_at);
  if start_value >= end_value then
    raise exception 'Khoảng thời gian Thi thật không hợp lệ.';
  end if;

  update public.real_exams
  set name = coalesce(nullif(trim(payload ->> 'name'), ''), name),
      start_at = start_value,
      end_at = end_value,
      question_percent = coalesce((payload ->> 'question_percent')::integer, question_percent),
      timer_seconds = coalesce((payload ->> 'timer_seconds')::integer, timer_seconds),
      multi_percent = coalesce((payload ->> 'multi_percent')::integer, multi_percent),
      max_attempts = coalesce((payload ->> 'max_attempts')::integer, max_attempts),
      scoring_method = coalesce((payload ->> 'scoring_method')::integer, scoring_method),
      updated_at = now()
  where id = target_real_exam_id
  returning * into target_exam;

  if payload ? 'sources' then
    perform public.replace_real_exam_sources(target_real_exam_id, payload -> 'sources');
  end if;
  generated_count := public.generate_real_exam_snapshot_unchecked(target_real_exam_id);
  return to_jsonb(target_exam) || jsonb_build_object('question_count', generated_count);
end;
$$;

create or replace function public.regenerate_real_exam_snapshot(target_real_exam_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
  generated_count integer;
begin
  select * into target_exam
  from public.real_exams
  where id = target_real_exam_id
  for update;
  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  if target_exam.hidden_at is not null
     or target_exam.ended_at is not null
     or now() >= target_exam.start_at
     or exists(select 1 from public.quiz_attempts where real_exam_id = target_real_exam_id) then
    raise exception 'Chỉ có thể tạo lại nguồn trước khi cuộc thi bắt đầu và chưa có kết quả.';
  end if;
  generated_count := public.generate_real_exam_snapshot_unchecked(target_real_exam_id);
  return jsonb_build_object('id', target_real_exam_id, 'question_count', generated_count);
end;
$$;

create or replace function public.end_real_exam(target_real_exam_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
begin
  select * into target_exam from public.real_exams where id = target_real_exam_id for update;
  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  if public.real_exam_status(target_exam) <> 'active' then
    raise exception 'Chỉ có thể kết thúc Đợt thi thật đang hoạt động.';
  end if;
  update public.real_exams
  set ended_at = coalesce(ended_at, now()), updated_at = now()
  where id = target_real_exam_id
  returning * into target_exam;
  return to_jsonb(target_exam);
end;
$$;

create or replace function public.hide_real_exam(target_real_exam_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
begin
  select * into target_exam from public.real_exams where id = target_real_exam_id for update;
  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  if target_exam.ended_at is null and now() <= target_exam.end_at then
    raise exception 'Chỉ có thể ẩn Đợt thi thật đã kết thúc.';
  end if;

  -- Loại bỏ toàn bộ nguồn câu hỏi của đợt thi thật này trong real_exam_sources để tránh lock ngân hàng câu hỏi
  delete from public.real_exam_sources where real_exam_id = target_real_exam_id;

  update public.real_exams
  set hidden_at = now(), hidden_by = auth.uid(), updated_at = now()
  where id = target_real_exam_id
  returning * into target_exam;
  return to_jsonb(target_exam);
end;
$$;

create or replace function public.list_real_exams(
  target_space_id bigint,
  requested_page integer default 1,
  requested_page_size integer default 15,
  search_text text default null,
  status_filter text default null
)
returns table (
  id bigint,
  code integer,
  name text,
  status text,
  start_at timestamptz,
  end_at timestamptz,
  question_count bigint,
  result_count bigint,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  safe_page integer := greatest(1, coalesce(requested_page, 1));
  safe_size integer := least(15, greatest(1, coalesce(requested_page_size, 15)));
begin
  if not public.can_manage_space(target_space_id) then
    raise exception 'Không có quyền quản lý Space này.';
  end if;
  return query
  with rows_with_status as (
    select exam.*, public.real_exam_status(exam) as computed_status
    from public.real_exams exam
    where exam.space_id = target_space_id
      and exam.hidden_at is null
      and (
        nullif(trim(search_text), '') is null
        or exam.name ilike '%' || trim(search_text) || '%'
        or exam.code::text = regexp_replace(search_text, '[^0-9]', '', 'g')
      )
  ),
  filtered as (
    select *
    from rows_with_status
    where nullif(status_filter, '') is null or computed_status = status_filter
  )
  select
    exam.id,
    exam.code,
    exam.name,
    exam.computed_status,
    exam.start_at,
    exam.end_at,
    (select count(*) from public.real_exam_question_refs ref where ref.real_exam_id = exam.id),
    (select count(*) from public.quiz_attempts attempt where attempt.real_exam_id = exam.id),
    count(*) over()
  from filtered exam
  order by
    case exam.computed_status when 'active' then 0 when 'scheduled' then 1 else 2 end,
    case when exam.computed_status = 'scheduled' then exam.start_at end asc,
    case when exam.computed_status <> 'scheduled' then exam.start_at end desc,
    exam.id desc
  limit safe_size
  offset (safe_page - 1) * safe_size;
end;
$$;

create or replace function public.get_real_exam_admin(target_real_exam_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
begin
  select * into target_exam from public.real_exams where id = target_real_exam_id;
  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền quản lý Đợt thi thật này.';
  end if;
  return to_jsonb(target_exam) || jsonb_build_object(
    'status', public.real_exam_status(target_exam),
    'question_count', (select count(*) from public.real_exam_question_refs where real_exam_id = target_real_exam_id),
    'result_count', (select count(*) from public.quiz_attempts where real_exam_id = target_real_exam_id),
    'sources', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', source.question_set_id,
        'name', source.question_set_name,
        'percent', source.percent
      ) order by source.question_set_name)
      from public.real_exam_sources source
      where source.real_exam_id = target_real_exam_id
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.get_real_exam_public(requested_code integer)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
  target_space public.spaces%rowtype;
begin
  select * into target_exam
  from public.real_exams
  where code = requested_code and hidden_at is null;
  if not found then
    return jsonb_build_object('exists', false);
  end if;
  select * into target_space from public.spaces where id = target_exam.space_id;
  if not target_space.published then
    return jsonb_build_object('exists', false);
  end if;
  return jsonb_build_object(
    'exists', true,
    'id', target_exam.id,
    'code', target_exam.code,
    'name', target_exam.name,
    'status', public.real_exam_status(target_exam),
    'start_at', target_exam.start_at,
    'end_at', target_exam.end_at,
    'timer_seconds', target_exam.timer_seconds,
    'max_attempts', target_exam.max_attempts,
    'scoring_method', target_exam.scoring_method,
    'space', jsonb_build_object(
      'id', target_space.id,
      'slug', target_space.slug,
      'name', target_space.name,
      'groups', coalesce((
        select jsonb_agg(group_row.name order by group_row.name)
        from public.groups group_row
        where group_row.space_id = target_space.id
      ), '[]'::jsonb)
    ),
    'questions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', question.question_code,
        'question_code', question.question_code,
        'type', question.type,
        'content', question.content,
        'options_json', question.options_json,
        'order_no', ref.generated_order
      ) order by ref.generated_order)
      from public.real_exam_question_refs ref
      join public.questions question on question.question_code = ref.question_code
      where ref.real_exam_id = target_exam.id
        and public.real_exam_status(target_exam) = 'active'
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.list_real_exam_results(
  target_real_exam_id bigint,
  result_limit integer default 20
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  target_exam public.real_exams%rowtype;
begin
  select * into target_exam from public.real_exams where id = target_real_exam_id;
  if not found or not public.can_manage_space(target_exam.space_id) then
    raise exception 'Không có quyền xem kết quả Đợt thi thật này.';
  end if;
  return coalesce((
    select jsonb_agg(to_jsonb(result_row) order by result_row.submitted_at desc)
    from (
      select
        attempt.id,
        target_exam.code as real_exam_code,
        target_exam.name as real_exam_name,
        attempt.group_name,
        attempt.student_name,
        attempt.score,
        attempt.total_questions,
        attempt.correct_count,
        attempt.wrong_count,
        attempt.duration_seconds,
        attempt.started_at,
        attempt.submitted_at
      from public.quiz_attempts attempt
      where attempt.real_exam_id = target_real_exam_id
      order by attempt.submitted_at desc
      limit least(5000, greatest(1, coalesce(result_limit, 20)))
    ) result_row
  ), '[]'::jsonb);
end;
$$;

create or replace function public.get_real_exam_attempt_count(
  requested_code integer,
  requested_student_name text
)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::integer
  from public.quiz_attempts attempt
  join public.real_exams exam on exam.id = attempt.real_exam_id
  where exam.code = requested_code
    and attempt.mode = 'real'
    and attempt.student_name_key = lower(trim(regexp_replace(coalesce(requested_student_name, ''), '\s+', ' ', 'g')))
$$;

create or replace function public.attach_real_exam_metadata()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_max_attempts integer;
  target_ended_at timestamptz;
begin
  if new.mode = 'real' and new.real_exam_code is not null then
    select
      exam.id,
      exam.code,
      exam.legacy_version,
      exam.name,
      exam.start_at,
      exam.end_at,
      exam.max_attempts,
      exam.ended_at
    into
      new.real_exam_id,
      new.real_exam_code,
      new.real_exam_version,
      new.real_exam_name,
      new.real_exam_start_at,
      new.real_exam_end_at,
      target_max_attempts,
      target_ended_at
    from public.real_exams exam
    where exam.code = new.real_exam_code
      and exam.hidden_at is null;
    if new.real_exam_id is null then
      raise exception 'Đợt thi thật không tồn tại.';
    end if;
    if new.started_at < new.real_exam_start_at
       or new.started_at > new.real_exam_end_at
       or (target_ended_at is not null and new.started_at > target_ended_at) then
      raise exception 'Lượt thi không bắt đầu trong thời gian Đợt thi thật.';
    end if;
    if (
      select count(*)
      from public.quiz_attempts attempt
      where attempt.real_exam_id = new.real_exam_id
        and attempt.student_name_key = new.student_name_key
    ) >= target_max_attempts then
      raise exception 'Học viên đã hết số lượt Thi thật.';
    end if;
  elsif new.mode = 'real' then
    select s.real_exam_version, s.real_exam_name, s.real_start_at, s.real_end_at
    into new.real_exam_version, new.real_exam_name, new.real_exam_start_at, new.real_exam_end_at
    from public.spaces s
    where s.slug = new.space_slug;
  else
    new.real_exam_id := null;
    new.real_exam_code := null;
    new.real_exam_version := null;
    new.real_exam_name := null;
    new.real_exam_start_at := null;
    new.real_exam_end_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists quiz_attempts_attach_real_exam_metadata on public.quiz_attempts;
create trigger quiz_attempts_attach_real_exam_metadata
before insert on public.quiz_attempts
for each row execute function public.attach_real_exam_metadata();

do $$
declare
  legacy_row record;
  allocated_code integer;
  created_exam_id bigint;
begin
  for legacy_row in
    select
      qa.space_slug,
      qa.real_exam_version,
      max(qa.real_exam_name) as real_exam_name,
      min(qa.real_exam_start_at) as start_at,
      max(qa.real_exam_end_at) as end_at,
      max(s.id) as space_id
    from public.quiz_attempts qa
    join public.spaces s on s.slug = qa.space_slug
    where qa.mode = 'real'
      and qa.real_exam_version is not null
      and not exists (
        select 1 from public.real_exams exam
        where exam.legacy_version = qa.real_exam_version
      )
    group by qa.space_slug, qa.real_exam_version
  loop
    allocated_code := public.allocate_real_exam_code();
    insert into public.real_exams(
      code, space_id, name, start_at, end_at, ended_at, legacy_version,
      scoring_method, created_at, updated_at
    )
    values (
      allocated_code,
      legacy_row.space_id,
      coalesce(nullif(legacy_row.real_exam_name, ''), 'Đợt thi thật lịch sử'),
      coalesce(legacy_row.start_at, now() - interval '1 hour'),
      greatest(
        coalesce(legacy_row.end_at, now()),
        coalesce(legacy_row.start_at, now() - interval '1 hour') + interval '1 minute'
      ),
      coalesce(legacy_row.end_at, now()),
      legacy_row.real_exam_version,
      2,
      now(),
      now()
    )
    returning id into created_exam_id;

    update public.quiz_attempts
    set real_exam_id = created_exam_id,
        real_exam_code = allocated_code
    where mode = 'real'
      and real_exam_version = legacy_row.real_exam_version
      and space_slug = legacy_row.space_slug;
  end loop;
end;
$$;

do $$
declare
  space_row record;
  target_exam_id bigint;
  allocated_code integer;
begin
  for space_row in
    select *
    from public.spaces
    where real_exam_enabled
      and real_start_at is not null
      and real_end_at is not null
      and real_start_at < real_end_at
  loop
    select exam.id
    into target_exam_id
    from public.real_exams exam
    where exam.legacy_version = space_row.real_exam_version;

    if target_exam_id is null then
      allocated_code := public.allocate_real_exam_code();
      insert into public.real_exams(
        code, space_id, name, start_at, end_at, question_percent, timer_seconds,
        multi_percent, max_attempts, scoring_method, legacy_version
      )
      values (
        allocated_code,
        space_row.id,
        coalesce(nullif(space_row.real_exam_name, ''), 'Đợt thi thật đã chuyển đổi'),
        space_row.real_start_at,
        space_row.real_end_at,
        space_row.real_question_percent,
        space_row.real_timer_seconds,
        space_row.real_multi_percent,
        space_row.real_max_attempts,
        coalesce(space_row.real_scoring_method, 2),
        space_row.real_exam_version
      )
      returning id into target_exam_id;
    else
      update public.real_exams
      set name = coalesce(nullif(space_row.real_exam_name, ''), name),
          start_at = space_row.real_start_at,
          end_at = space_row.real_end_at,
          ended_at = case when now() > space_row.real_end_at then coalesce(ended_at, space_row.real_end_at) else null end,
          question_percent = space_row.real_question_percent,
          timer_seconds = space_row.real_timer_seconds,
          multi_percent = space_row.real_multi_percent,
          max_attempts = space_row.real_max_attempts,
          scoring_method = coalesce(space_row.real_scoring_method, 2),
          updated_at = now()
      where id = target_exam_id;
    end if;

    begin
      perform public.replace_real_exam_sources(target_exam_id, space_row.real_question_sets);
      perform public.generate_real_exam_snapshot_unchecked(target_exam_id);
    exception when others then
      raise notice 'Không thể tạo snapshot cho Space %: %', space_row.slug, sqlerrm;
    end;
  end loop;
end;
$$;

create or replace function public.cleanup_space_results_unchecked(target_space_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_slug text;
  mock_days integer;
  deleted_mock_by_days integer := 0;
  deleted_mock_by_cap integer := 0;
begin
  select s.slug, coalesce(s.mock_result_retention_days, 7)
  into target_slug, mock_days
  from public.spaces s
  where s.id = target_space_id;

  if target_slug is null then
    raise exception 'Space không tồn tại.';
  end if;

  delete from public.quiz_attempts attempt
  where attempt.space_slug = target_slug
    and attempt.mode = 'mock'
    and attempt.submitted_at < now() - make_interval(days => mock_days);
  get diagnostics deleted_mock_by_days = row_count;

  with old_mock as (
    select attempt.id
    from public.quiz_attempts attempt
    where attempt.space_slug = target_slug and attempt.mode = 'mock'
    order by attempt.submitted_at desc
    offset 500
  )
  delete from public.quiz_attempts attempt
  using old_mock
  where attempt.id = old_mock.id;
  get diagnostics deleted_mock_by_cap = row_count;

  return jsonb_build_object(
    'ok', true,
    'mock_deleted_by_days', deleted_mock_by_days,
    'mock_deleted_by_cap', deleted_mock_by_cap,
    'real_deleted_by_exams', 0,
    'real_deleted_by_cap', 0
  );
end;
$$;

alter table public.real_exams enable row level security;
alter table public.real_exam_sources enable row level security;
alter table public.real_exam_question_refs enable row level security;

drop policy if exists "question sets public read published" on public.question_sets;
create policy "question sets public read published"
on public.question_sets for select to anon
using (
  hidden_at is null
  and exists (select 1 from public.spaces space where space.id = space_id and space.published)
);

drop policy if exists "questions public read published" on public.questions;
create policy "questions public read published"
on public.questions for select to anon
using (
  hidden_at is null
  and exists (select 1 from public.spaces space where space.id = space_id and space.published)
);

drop policy if exists "real exams admins read" on public.real_exams;
create policy "real exams admins read"
on public.real_exams for select to authenticated
using (public.can_manage_space(space_id));

drop policy if exists "real exam sources admins read" on public.real_exam_sources;
create policy "real exam sources admins read"
on public.real_exam_sources for select to authenticated
using (
  exists (
    select 1 from public.real_exams exam
    where exam.id = real_exam_id and public.can_manage_space(exam.space_id)
  )
);

drop policy if exists "real exam refs admins read" on public.real_exam_question_refs;
create policy "real exam refs admins read"
on public.real_exam_question_refs for select to authenticated
using (
  exists (
    select 1 from public.real_exams exam
    where exam.id = real_exam_id and public.can_manage_space(exam.space_id)
  )
);

revoke all on public.question_code_registry, public.real_exam_code_registry from anon, authenticated;
revoke all on public.real_exams, public.real_exam_sources, public.real_exam_question_refs from anon;
grant select on public.real_exams, public.real_exam_sources, public.real_exam_question_refs to authenticated;

revoke all on function public.allocate_question_code(bigint) from public;
revoke all on function public.allocate_real_exam_code() from public;
revoke all on function public.generate_real_exam_snapshot_unchecked(bigint) from public;
revoke all on function public.replace_real_exam_sources(bigint, jsonb) from public;

revoke all on function public.create_real_exam(bigint, jsonb) from public;
grant execute on function public.create_real_exam(bigint, jsonb) to authenticated;
revoke all on function public.update_real_exam(bigint, jsonb) from public;
grant execute on function public.update_real_exam(bigint, jsonb) to authenticated;
revoke all on function public.regenerate_real_exam_snapshot(bigint) from public;
grant execute on function public.regenerate_real_exam_snapshot(bigint) to authenticated;
revoke all on function public.end_real_exam(bigint) from public;
grant execute on function public.end_real_exam(bigint) to authenticated;
revoke all on function public.hide_real_exam(bigint) from public;
grant execute on function public.hide_real_exam(bigint) to authenticated;
revoke all on function public.list_real_exams(bigint, integer, integer, text, text) from public;
grant execute on function public.list_real_exams(bigint, integer, integer, text, text) to authenticated;
revoke all on function public.get_real_exam_admin(bigint) from public;
grant execute on function public.get_real_exam_admin(bigint) to authenticated;
revoke all on function public.get_real_exam_public(integer) from public;
grant execute on function public.get_real_exam_public(integer) to anon, authenticated;
revoke all on function public.list_real_exam_results(bigint, integer) from public;
grant execute on function public.list_real_exam_results(bigint, integer) to authenticated;
revoke all on function public.get_real_exam_attempt_count(integer, text) from public;
grant execute on function public.get_real_exam_attempt_count(integer, text) to anon, authenticated;

notify pgrst, 'reload schema';

commit;
